### PR TITLE
Initial bootstrapping with common utilities and some hardening

### PR DESCRIPTION
**Pull request by mblomdahl**
@vtepliuk Please review!

@akebrissman, @carlba; now joining the cool crowd, gotten my first self-hosted server in long time. :) Any security hardening tips for keeping this server publicly accessible? I'm getting a hundred hack-in attempts daily so far..

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looking good :)

**Comment by mblomdahl** [comment]
@vtepliuk Also added git-2.16.5 via IUS (we have 2.17-ish on macOS). CentOS built-in is very old, 1.8-something.. Can you verify you're able to login to the server?

**Comment by carlba** [comment]
Why are you punisishing yourself with running CentOS. Just run Ubuntu instead and avoid lots of headaches :)

**Comment by ghost** [comment]
> @vtepliuk Also added git-2.16.5 via IUS (we have 2.17-ish on macOS). CentOS built-in is very old, 1.8-something.. Can you verify you're able to login to the server?

I am able to login.

**Pull request merged**
